--!strict
-- @theonlyflare

-- SimpleShake/Presets

local Types = require(script.Parent:WaitForChild("Types")) 

local Presets: { [string]: Types.ShakeProfile } = {
	Explosion = { Amplitude = 3.0, Frequency = 20, Duration = 0.5, FadeIn = 0.05, FadeOut = 0.8 },
	Footstep_Heavy = { Amplitude = 0.8, Frequency = 12, Duration = 0.2, FadeIn = 0.05, FadeOut = 0.15 },
	Footstep_Light = { Amplitude = 0.3, Frequency = 15, Duration = 0.15, FadeIn = 0.02, FadeOut = 0.1 },
	Melee_Hit = { Amplitude = 1.5, Frequency = 25, Duration = 0.2, FadeIn = 0.02, FadeOut = 0.3 },
	Earthquake = { Amplitude = 1.2, Frequency = 10, Duration = math.huge, FadeIn = 1.0, FadeOut = 2.0 },
	Heartbeat = { Amplitude = 0.5, Frequency = 5, Duration = math.huge, FadeIn = 0.5, FadeOut = 0.5 },
	Recoil_Light = { Amplitude = 0.5, Frequency = 30, Duration = 0.1, FadeIn = 0.01, FadeOut = 0.1 },
	Recoil_Heavy = { Amplitude = 2.0, Frequency = 35, Duration = 0.15, FadeIn = 0.01, FadeOut = 0.2 },
	Vehicle_Rumble = { Amplitude = 0.4, Frequency = 40, Duration = math.huge, FadeIn = 0.5, FadeOut = 0.5 },
	Landing = { Amplitude = 2.5, Frequency = 15, Duration = 0.3, FadeIn = 0.02, FadeOut = 0.4 }
}

return Presets
